ci:
  autofix_prs: true
  autofix_commit_msg: "chore(pre-commit.ci): Fixing issues with pre-commit"
  autoupdate_commit_msg: "chore(pre-commit.ci): pre-commit automatically updated revs."
  autoupdate_schedule: weekly
  skip: []
  submodules: false
default_stages:
  - pre-commit
exclude: ^docs/|/migrations/
repos:
  - hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: detect-private-key
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
  - repo: https://gitlab.com/bmares/check-json5
    rev: v1.0.0
    hooks:
      - id: check-json5
  - hooks:
      - args:
          - --target-version
          - "4.2"
        id: django-upgrade
    repo: https://github.com/adamchainz/django-upgrade
    rev: 1.22.2
  - hooks:
      - args:
          - --py311-plus
        id: pyupgrade
    repo: https://github.com/asottile/pyupgrade
    rev: v3.19.1
  - hooks:
      - id: black
    repo: https://github.com/psf/black
    rev: 24.10.0
  - hooks:
      - id: isort
    repo: https://github.com/PyCQA/isort
    rev: 5.13.2
  - hooks:
      - id: flake8
    repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
  - hooks:
      - id: djlint-reformat-django
      - id: djlint-django
    repo: https://github.com/Riverside-Healthcare/djLint
    rev: v1.36.4
  - hooks:
      - id: commitizen
      - id: commitizen-branch
        stages:
          - pre-push
    repo: https://github.com/commitizen-tools/commitizen
    rev: v4.1.0
